### ISSUE TITLE
On which hardware is this project tested?

### ISSUE THREAD

**Issue by andreas-bauer** [NelsonBrandao/waveshare-7in5v2#2]
I'm unable to run the given examples from the `README`.
In my setup, the display is connected through the hat to a Raspberry Pi 4.
I'm able to run the C and Python `EPD_7in5_V2` examples by Waveshare, but I'm not able to run this project.
If I execute a build binary with sudo rights, the display is white with a thin black border.

On which hardware did you test your setup, and are there any steps that need to be done but need to be documented?

**Comment by NelsonBrandao** [comment]
Sorry, I must have missed the email notification about this issue.

I'm using the Waveshare 7in5 v2 [back and white version](https://www.waveshare.com/7.5inch-e-paper-hat.htm) on a raspberry pi zero.

Since the original issue is very old I'm going to close it. If you still have problems create a new issue please.
